In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("SMSSpamCollection.txt",sep="\t",names=["labels","message"])

In [4]:
df.head()

labels                                            message
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
import re
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
wordnet=WordNetLemmatizer()

In [8]:
corpus=[]
for i in range (0,len(df)):
    review=re.sub("[^a-zA-Z]"," ",df["message"][i])
    review=review.lower()
    review=review.split()
    review=[wordnet.lemmatize(word) for word in review if word not in set(stopwords.words("english"))]
    review=" ".join(review)
    corpus.append(review)

## using Bag of words

In [23]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
x=cv.fit_transform(corpus).toarray()

## Label encoding

In [24]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
y=lb.fit_transform(df["labels"])
y

array([0, 0, 1, ..., 0, 0, 0])

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)

 ## using naive bayes for classification

In [26]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
classify=model.fit(x_train,y_train)

In [27]:
y_pred=classify.predict(x_test)

In [29]:
y_pred

array([0, 1, 0, ..., 0, 1, 0])

In [30]:
y_test

array([0, 1, 0, ..., 0, 1, 0])

In [33]:
from sklearn.metrics import confusion_matrix
confusion_m=confusion_matrix(y_test,y_pred)
confusion_m

array([[936,  19],
       [  7, 153]])

In [37]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,y_pred)
acc

0.9766816143497757

## using tfidf vector for classifying the message as sapm or ham 

In [40]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer()
z=tf.fit_transform(corpus).toarray()

In [41]:
z_train,z_test,y_train,y_test=train_test_split(z,y,test_size=0.2,random_state=0)
tfclass=model.fit(z_train,y_train)

In [42]:
tf_pred=tfclass.predict(x_test)

In [43]:
tf_pred

array([0, 1, 0, ..., 0, 1, 0])

In [44]:
y_test

array([0, 1, 0, ..., 0, 1, 0])

In [46]:
con=confusion_matrix(y_test,tf_pred)
con

array([[945,  10],
       [ 15, 145]])

In [48]:
score=accuracy_score(y_test,tf_pred)
score

0.9775784753363229